import Image from "next/image";
import Logo from "./component-home/assets/Logomark.svg";
import { Button } from "@/components/ui/button";
import SearchBar from "./component-home/searchBar";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={plusJakartaSans.style} className="bg-customBackground">
        {children}
      </body>
    </html>
  );
}
